-- FIFA Women's Ranking: https://www.fifa.com/fifa-world-ranking/women?dateId=ranking_20230609

INSERT INTO tb_team (id, name, score) VALUES ('ARG', 'Argentina', 1682.45);
INSERT INTO tb_team (id, name, score) VALUES ('AUS', 'Australia', 1919.69);
INSERT INTO tb_team (id, name, score) VALUES ('BRA', 'Brazil', 1995.3);
INSERT INTO tb_team (id, name, score) VALUES ('CAN', 'Canada', 1996.34);
INSERT INTO tb_team (id, name, score) VALUES ('CHN', 'China PR', 1854.49);
INSERT INTO tb_team (id, name, score) VALUES ('COL', 'Colombia', 1702.64);
INSERT INTO tb_team (id, name, score) VALUES ('CRC', 'Costa Rica', 1596.94);
INSERT INTO tb_team (id, name, score) VALUES ('DEN', 'Denmark', 1866.25);
INSERT INTO tb_team (id, name, score) VALUES ('ENG', 'England', 2040.76);
INSERT INTO tb_team (id, name, score) VALUES ('FRA', 'France', 2026.65);
INSERT INTO tb_team (id, name, score) VALUES ('GER', 'Germany', 2061.56);
INSERT INTO tb_team (id, name, score) VALUES ('HAI', 'Haiti', 1475.33);
INSERT INTO tb_team (id, name, score) VALUES ('ITA', 'Italy', 1846.5);
INSERT INTO tb_team (id, name, score) VALUES ('JAM', 'Jamaica', 1536.81);
INSERT INTO tb_team (id, name, score) VALUES ('JPN', 'Japan', 1916.68);
INSERT INTO tb_team (id, name, score) VALUES ('KOR', 'Korea Republic', 1840.27);
INSERT INTO tb_team (id, name, score) VALUES ('MAR', 'Morocco', 1334.08);
INSERT INTO tb_team (id, name, score) VALUES ('NED', 'Netherlands', 1980.47);
INSERT INTO tb_team (id, name, score) VALUES ('NZL', 'New Zealand', 1699.7);
INSERT INTO tb_team (id, name, score) VALUES ('NGA', 'Nigeria', 1554.94);
INSERT INTO tb_team (id, name, score) VALUES ('NOR', 'Norway', 1908.25);
INSERT INTO tb_team (id, name, score) VALUES ('PAN', 'Panama', 1482.51);
INSERT INTO tb_team (id, name, score) VALUES ('PHI', 'Philippines', 1512.97);
INSERT INTO tb_team (id, name, score) VALUES ('POR', 'Portugal', 1745.13);
INSERT INTO tb_team (id, name, score) VALUES ('IRL', 'Republic of Ireland', 1743.59);
INSERT INTO tb_team (id, name, score) VALUES ('RSA', 'South Africa', 1471.52);
INSERT INTO tb_team (id, name, score) VALUES ('ESP', 'Spain', 2002.28);
INSERT INTO tb_team (id, name, score) VALUES ('SWE', 'Sweden', 2049.71);
INSERT INTO tb_team (id, name, score) VALUES ('SUI', 'Switzerland', 1765.9);
INSERT INTO tb_team (id, name, score) VALUES ('USA', 'USA', 2090.03);
INSERT INTO tb_team (id, name, score) VALUES ('VIE', 'Vietnam', 1648.89);
INSERT INTO tb_team (id, name, score) VALUES ('ZAM', 'Zambia', 1298.31);
